// resources/js/layouts/AuthLayout.tsx
import type { ReactNode } from 'react';

export function AuthLayout({ children }: { children: ReactNode }) {
    return (
        <div className="min-h-screen px-4 py-10 sm:px-6 lg:px-8">
            <div className="mx-auto flex min-h-[calc(100vh-5rem)] max-w-6xl items-center justify-center rounded-[2rem] border border-slate-200/70 bg-white/80 p-6 shadow-[0_30px_80px_-50px_rgba(15,23,42,0.4)] backdrop-blur">
                <div className="w-full max-w-md">{children}</div>
            </div>
        </div>
    );
}

// backend/resources/js/layouts/AuthLayout.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-100 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
      <div class="text-center">
        <h1 class="text-3xl font-bold text-gray-900">AutoERP</h1>
        <p class="mt-2 text-sm text-gray-600">Enterprise Resource Planning</p>
      </div>

      <div class="bg-white shadow-md rounded-lg p-8">
        <router-view />
      </div>
    </div>
  </div>
</template>

<script setup>
</script>
