// resources/js/components/Pagination.vue
<template>
  <div
    v-if="meta && meta.last_page > 1"
    class="flex items-center justify-between px-4 py-3 border-t border-gray-200 dark:border-gray-800"
  >
    <p class="text-sm text-gray-500 dark:text-gray-400">
      Page <span class="font-medium text-gray-900 dark:text-white">{{ meta.current_page }}</span>
      of <span class="font-medium text-gray-900 dark:text-white">{{ meta.last_page }}</span>
      <span v-if="meta.total"> · {{ meta.total }} total</span>
    </p>
    <div class="flex gap-2">
      <button
        type="button"
        :disabled="meta.current_page <= 1"
        class="inline-flex items-center rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-1.5 text-xs font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
        aria-label="Previous page"
        @click="$emit('change', meta.current_page - 1)"
      >
        ← Prev
      </button>
      <button
        type="button"
        :disabled="meta.current_page >= meta.last_page"
        class="inline-flex items-center rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-1.5 text-xs font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
        aria-label="Next page"
        @click="$emit('change', meta.current_page + 1)"
      >
        Next →
      </button>
    </div>
  </div>
</template>

<script setup>
defineProps({
    meta: {
        type: Object,
        default: null,
    },
});

defineEmits(['change']);
</script>

// resources/js/shared/components/Pagination.tsx
import type { PaginationMeta } from '@/shared/types/pagination';
import { Button } from './Button';

export function Pagination({ meta, onPageChange }: {
    meta?: PaginationMeta;
    onPageChange: (page: number) => void;
}) {
    if (!meta || meta.last_page <= 1) return null;

    return (
        <nav className="mt-4 flex items-center justify-between gap-3 text-sm text-slate-600" aria-label="Pagination">
            <span>
                {meta.from ?? 0}-{meta.to ?? 0} of {meta.total}
                <span className="sr-only">. Page {meta.current_page} of {meta.last_page}.</span>
            </span>
            <div className="flex items-center gap-2">
                <Button
                    variant="secondary"
                    disabled={meta.current_page <= 1}
                    aria-label={`Go to page ${Math.max(1, meta.current_page - 1)}`}
                    onClick={() => onPageChange(meta.current_page - 1)}
                >
                    Previous
                </Button>
                <span aria-current="page" className="min-w-20 text-center font-medium text-slate-700">
                    {meta.current_page} / {meta.last_page}
                </span>
                <Button
                    variant="secondary"
                    disabled={meta.current_page >= meta.last_page}
                    aria-label={`Go to page ${Math.min(meta.last_page, meta.current_page + 1)}`}
                    onClick={() => onPageChange(meta.current_page + 1)}
                >
                    Next
                </Button>
            </div>
        </nav>
    );
}
