// resources/js/modules/auth/LoginPage.tsx
import { useEffect, useState } from 'react';
import { Navigate, useLocation, useNavigate } from 'react-router-dom';
import { ApiError, fieldError } from '@/shared/api/apiError';
import { Button } from '@/shared/components/Button';
import { ErrorAlert } from '@/shared/components/ErrorAlert';
import { Input } from '@/shared/components/Input';
import { LoadingState } from '@/shared/components/LoadingState';
import { useAuth } from './AuthProvider';

export default function LoginPage() {
    const auth = useAuth();
    const navigate = useNavigate();
    const location = useLocation();
    const [loginIdentifier, setLoginIdentifier] = useState('');
    const [password, setPassword] = useState('');
    const [error, setError] = useState<ApiError | null>(null);
    const [submitting, setSubmitting] = useState(false);

    useEffect(() => {
        document.title = 'Login - AutoERP';
    }, []);

    if (auth.isLoading && auth.token && !auth.user) {
        return <LoadingState label="Checking your session..." fullPage />;
    }

    if (auth.isAuthenticated) {
        return <Navigate to="/dashboard" replace />;
    }

    const from = location.state && typeof location.state === 'object' && 'from' in location.state
        ? String(location.state.from)
        : '/dashboard';

    return (
        <main className="flex min-h-screen items-center justify-center bg-slate-100 px-4 py-10">
            <section className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
                <div className="mb-6">
                    <p className="text-sm font-semibold uppercase tracking-wide text-sky-600">AutoERP</p>
                    <h1 className="mt-2 text-2xl font-bold text-slate-950">Sign in</h1>
                    <p className="mt-2 text-sm text-slate-500">
                        Use your AutoERP account.
                    </p>
                </div>

                <form
                    className="space-y-4"
                    onSubmit={async (event) => {
                        event.preventDefault();
                        setError(null);
                        setSubmitting(true);

                        try {
                            await auth.login({
                                login_identifier: loginIdentifier,
                                password,
                            });
                            navigate(from, { replace: true });
                        } catch (nextError) {
                            setError(nextError instanceof ApiError
                                ? nextError
                                : new ApiError('Login failed.', null));
                        } finally {
                            setSubmitting(false);
                        }
                    }}
                >
                    <ErrorAlert error={error} title="Unable to sign in" />
                    <Input
                        label="Email or username"
                        name="login_identifier"
                        autoComplete="username"
                        value={loginIdentifier}
                        onChange={(event) => setLoginIdentifier(event.target.value)}
                        error={fieldError(error, 'login_identifier') ?? fieldError(error, 'email')}
                        required
                    />
                    <Input
                        label="Password"
                        name="password"
                        type="password"
                        autoComplete="current-password"
                        value={password}
                        onChange={(event) => setPassword(event.target.value)}
                        error={fieldError(error, 'password')}
                        required
                    />
                    <Button type="submit" className="w-full" loading={submitting || auth.isLoading}>
                        Sign in
                    </Button>
                </form>
            </section>
        </main>
    );
}

// resources/js/pages/LoginPage.vue
<template>
  <div>
    <div class="text-center mb-6">
      <h2 class="text-xl font-bold text-gray-900">Sign in to your account</h2>
      <p class="text-sm text-gray-500 mt-1">Enter your credentials to continue</p>
    </div>

    <form class="space-y-5" @submit.prevent="handleLogin">
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1" for="login-email">Email</label>
        <input
          id="login-email"
          v-model="form.email"
          type="email"
          required
          autocomplete="email"
          class="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          placeholder="you@example.com"
        />
      </div>

      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1" for="login-password"
          >Password</label
        >
        <input
          id="login-password"
          v-model="form.password"
          type="password"
          required
          autocomplete="current-password"
          class="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          placeholder="••••••••"
        />
      </div>

      <div
        v-if="error"
        class="flex items-center gap-2 bg-red-50 border border-red-200 text-red-700 text-sm rounded-lg px-3 py-2"
        role="alert"
      >
        <span aria-hidden="true">❌</span>
        <span>{{ error }}</span>
      </div>

      <button
        type="submit"
        :disabled="loading"
        class="w-full flex items-center justify-center gap-2 bg-blue-600 text-white py-2.5 rounded-lg text-sm font-medium hover:bg-blue-700 disabled:opacity-60 transition-colors"
      >
        <AppSpinner v-if="loading" size="sm" />
        <span>{{ loading ? 'Signing in…' : 'Sign In' }}</span>
      </button>
    </form>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { useAuthStore } from '@/stores/auth';
import AppSpinner from '@/components/AppSpinner.vue';
import type { ApiError } from '@/types/index';

const router = useRouter();
const route = useRoute();
const auth = useAuthStore();

const form = ref({ email: '', password: '' });
const error = ref<string | null>(null);
const loading = ref(false);

async function handleLogin(): Promise<void> {
  error.value = null;
  loading.value = true;
  try {
    await auth.login(form.value.email, form.value.password);
    const redirect = (route.query.redirect as string | undefined) ?? '/dashboard';
    await router.push(redirect);
  } catch (e: unknown) {
    const axiosError = e as { response?: { data?: ApiError } };
    error.value = axiosError.response?.data?.message ?? 'Login failed. Please try again.';
  } finally {
    loading.value = false;
  }
}
</script>
