// resources/js/components/ui/StatCard.tsx
interface StatCardProps {
    label: string;
    value: string;
    tone?: 'brand' | 'slate' | 'amber';
}

const toneStyles = {
    brand: 'from-brand-500/15 to-brand-700/10 border-brand-500/20 text-brand-900',
    slate: 'from-slate-100 to-slate-50 border-slate-200 text-slate-900',
    amber: 'from-amber-100 to-orange-50 border-amber-200 text-amber-900',
} as const;

export function StatCard({ label, value, tone = 'brand' }: StatCardProps) {
    return (
        <article className={`rounded-[1.5rem] border bg-gradient-to-br p-5 shadow-sm ${toneStyles[tone]}`}>
            <div className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">{label}</div>
            <div className="mt-3 text-sm leading-6">{value}</div>
        </article>
    );
}

// resources/js/components/StatCard.vue
<template>
  <div
    class="bg-white rounded-lg shadow p-5 border-l-4"
    :class="`border-${color}-500`"
  >
    <p class="text-sm text-gray-500">{{ label }}</p>
    <p class="text-2xl font-bold text-gray-800 mt-1">{{ value }}</p>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  label: string;
  value: string | number;
  color?: string;
}>();
</script>
