// resources/js/layouts/AuthLayout.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-950 px-4 py-12">
    <div class="w-full max-w-md">
      <div class="text-center mb-8">
        <h1 class="text-2xl font-bold text-gray-900 dark:text-white">AutoERP</h1>
        <p class="text-sm text-gray-500 dark:text-gray-400 mt-1">Multi-tenant SaaS CRM / ERP Platform</p>
      </div>
      <div class="bg-white dark:bg-gray-900 rounded-xl shadow-sm border border-gray-200 dark:border-gray-800 p-8">
        <slot />
      </div>
    </div>
  </div>
</template>

// resources/js/layouts/AuthLayout.tsx
import type { ReactNode } from 'react';

export function AuthLayout({ children }: { children: ReactNode }) {
    return (
        <div className="min-h-screen px-4 py-10 sm:px-6 lg:px-8">
            <div className="mx-auto flex min-h-[calc(100vh-5rem)] max-w-6xl items-center justify-center rounded-[2rem] border border-slate-200/70 bg-white/80 p-6 shadow-[0_30px_80px_-50px_rgba(15,23,42,0.4)] backdrop-blur">
                <div className="w-full max-w-md">{children}</div>
            </div>
        </div>
    );
}
