// frontend/src/components/layouts/AuthLayout.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-primary-500 to-primary-700">
    <div class="w-full max-w-md">
      <div class="bg-white rounded-2xl shadow-2xl p-8">
        <div class="text-center mb-8">
          <h1 class="text-3xl font-bold text-primary-600">AutoERP</h1>
          <p class="text-secondary-600 mt-2">{{ $t('auth.loginSubtitle') }}</p>
        </div>
        <router-view />
      </div>
    </div>
  </div>
</template>

<script setup>
</script>

// resources/js/layouts/AuthLayout.tsx
import type { ReactNode } from 'react';

export function AuthLayout({ children }: { children: ReactNode }) {
    return (
        <div className="min-h-screen px-4 py-10 sm:px-6 lg:px-8">
            <div className="mx-auto flex min-h-[calc(100vh-5rem)] max-w-6xl items-center justify-center rounded-[2rem] border border-slate-200/70 bg-white/80 p-6 shadow-[0_30px_80px_-50px_rgba(15,23,42,0.4)] backdrop-blur">
                <div className="w-full max-w-md">{children}</div>
            </div>
        </div>
    );
}
